POST http://localhost:3000/api/load-random-buses HTTP/1.1
content-type: application/json

[
{"busNumber":1000,"id":"","plateNumber":460444},
{"busNumber":999,"id":"","plateNumber":976191},
{"busNumber":998,"id":"","plateNumber":755706},
{"busNumber":997,"id":"","plateNumber":365186},
{"busNumber":996,"id":"","plateNumber":938400},
{"busNumber":995,"id":"","plateNumber":484651},
{"busNumber":994,"id":"","plateNumber":724743},
{"busNumber":993,"id":"","plateNumber":761360},
{"busNumber":992,"id":"","plateNumber":658348},
{"busNumber":991,"id":"","plateNumber":232637},
{"busNumber":990,"id":"","plateNumber":881258},
{"busNumber":989,"id":"","plateNumber":666506},
{"busNumber":988,"id":"","plateNumber":859475},
{"busNumber":987,"id":"","plateNumber":441994},
{"busNumber":986,"id":"","plateNumber":842742},
{"busNumber":985,"id":"","plateNumber":745549},
{"busNumber":984,"id":"","plateNumber":122044},
{"busNumber":983,"id":"","plateNumber":493123},
{"busNumber":982,"id":"","plateNumber":302717},
{"busNumber":981,"id":"","plateNumber":271502},
{"busNumber":980,"id":"","plateNumber":131293},
{"busNumber":979,"id":"","plateNumber":39565},
{"busNumber":978,"id":"","plateNumber":787382},
{"busNumber":977,"id":"","plateNumber":800957},
{"busNumber":976,"id":"","plateNumber":46858},
{"busNumber":975,"id":"","plateNumber":725307},
{"busNumber":974,"id":"","plateNumber":761701},
{"busNumber":973,"id":"","plateNumber":25461},
{"busNumber":972,"id":"","plateNumber":236461},
{"busNumber":971,"id":"","plateNumber":580039},
{"busNumber":970,"id":"","plateNumber":58004},
{"busNumber":969,"id":"","plateNumber":566338},
{"busNumber":968,"id":"","plateNumber":850980},
{"busNumber":967,"id":"","plateNumber":809720},
{"busNumber":966,"id":"","plateNumber":409171},
{"busNumber":965,"id":"","plateNumber":734891},
{"busNumber":964,"id":"","plateNumber":619766},
{"busNumber":963,"id":"","plateNumber":899418},
{"busNumber":962,"id":"","plateNumber":452470},
{"busNumber":961,"id":"","plateNumber":168196},
{"busNumber":960,"id":"","plateNumber":601723},
{"busNumber":959,"id":"","plateNumber":52849},
{"busNumber":958,"id":"","plateNumber":971236},
{"busNumber":957,"id":"","plateNumber":450510},
{"busNumber":956,"id":"","plateNumber":778386},
{"busNumber":955,"id":"","plateNumber":369183},
{"busNumber":954,"id":"","plateNumber":17994},
{"busNumber":953,"id":"","plateNumber":256833},
{"busNumber":952,"id":"","plateNumber":656972},
{"busNumber":951,"id":"","plateNumber":82605},
{"busNumber":950,"id":"","plateNumber":674173},
{"busNumber":949,"id":"","plateNumber":41918},
{"busNumber":948,"id":"","plateNumber":212456},
{"busNumber":947,"id":"","plateNumber":710287},
{"busNumber":946,"id":"","plateNumber":369843},
{"busNumber":945,"id":"","plateNumber":976907},
{"busNumber":944,"id":"","plateNumber":135707},
{"busNumber":943,"id":"","plateNumber":285179},
{"busNumber":942,"id":"","plateNumber":512829},
{"busNumber":941,"id":"","plateNumber":855679},
{"busNumber":940,"id":"","plateNumber":285191},
{"busNumber":939,"id":"","plateNumber":488549},
{"busNumber":938,"id":"","plateNumber":655101},
{"busNumber":937,"id":"","plateNumber":629494},
{"busNumber":936,"id":"","plateNumber":423410},
{"busNumber":935,"id":"","plateNumber":146293},
{"busNumber":934,"id":"","plateNumber":410815},
{"busNumber":933,"id":"","plateNumber":677133},
{"busNumber":932,"id":"","plateNumber":569637},
{"busNumber":931,"id":"","plateNumber":188197},
{"busNumber":930,"id":"","plateNumber":261202},
{"busNumber":929,"id":"","plateNumber":310662},
{"busNumber":928,"id":"","plateNumber":149384},
{"busNumber":927,"id":"","plateNumber":89558},
{"busNumber":926,"id":"","plateNumber":13495},
{"busNumber":925,"id":"","plateNumber":891027},
{"busNumber":924,"id":"","plateNumber":900793},
{"busNumber":923,"id":"","plateNumber":740530},
{"busNumber":922,"id":"","plateNumber":116377},
{"busNumber":921,"id":"","plateNumber":392059},
{"busNumber":920,"id":"","plateNumber":668132},
{"busNumber":919,"id":"","plateNumber":943916},
{"busNumber":918,"id":"","plateNumber":390716},
{"busNumber":917,"id":"","plateNumber":658187},
{"busNumber":916,"id":"","plateNumber":630414},
{"busNumber":915,"id":"","plateNumber":163869},
{"busNumber":914,"id":"","plateNumber":231813},
{"busNumber":913,"id":"","plateNumber":818135},
{"busNumber":912,"id":"","plateNumber":313002},
{"busNumber":911,"id":"","plateNumber":489448},
{"busNumber":910,"id":"","plateNumber":15711},
{"busNumber":909,"id":"","plateNumber":393207},
{"busNumber":908,"id":"","plateNumber":901521},
{"busNumber":907,"id":"","plateNumber":453448},
{"busNumber":906,"id":"","plateNumber":653847},
{"busNumber":905,"id":"","plateNumber":948917},
{"busNumber":904,"id":"","plateNumber":704483},
{"busNumber":903,"id":"","plateNumber":31090},
{"busNumber":902,"id":"","plateNumber":220351},
{"busNumber":901,"id":"","plateNumber":56409},
{"busNumber":900,"id":"","plateNumber":778582},
{"busNumber":899,"id":"","plateNumber":799803},
{"busNumber":898,"id":"","plateNumber":13349},
{"busNumber":897,"id":"","plateNumber":4363},
{"busNumber":896,"id":"","plateNumber":271006},
{"busNumber":895,"id":"","plateNumber":727256},
{"busNumber":894,"id":"","plateNumber":613357},
{"busNumber":893,"id":"","plateNumber":567961},
{"busNumber":892,"id":"","plateNumber":208545},
{"busNumber":891,"id":"","plateNumber":952013},
{"busNumber":890,"id":"","plateNumber":910611},
{"busNumber":889,"id":"","plateNumber":956427},
{"busNumber":888,"id":"","plateNumber":65148},
{"busNumber":887,"id":"","plateNumber":279950},
{"busNumber":886,"id":"","plateNumber":506261},
{"busNumber":885,"id":"","plateNumber":849976},
{"busNumber":884,"id":"","plateNumber":896426},
{"busNumber":883,"id":"","plateNumber":741855},
{"busNumber":882,"id":"","plateNumber":761777},
{"busNumber":881,"id":"","plateNumber":970702},
{"busNumber":880,"id":"","plateNumber":40071},
{"busNumber":879,"id":"","plateNumber":691434},
{"busNumber":878,"id":"","plateNumber":24938},
{"busNumber":877,"id":"","plateNumber":265290},
{"busNumber":876,"id":"","plateNumber":127513},
{"busNumber":875,"id":"","plateNumber":508732},
{"busNumber":874,"id":"","plateNumber":60301},
{"busNumber":873,"id":"","plateNumber":381173},
{"busNumber":872,"id":"","plateNumber":735434},
{"busNumber":871,"id":"","plateNumber":913804},
{"busNumber":870,"id":"","plateNumber":1755},
{"busNumber":869,"id":"","plateNumber":37383},
{"busNumber":868,"id":"","plateNumber":423858},
{"busNumber":867,"id":"","plateNumber":284258},
{"busNumber":866,"id":"","plateNumber":639246},
{"busNumber":865,"id":"","plateNumber":346337},
{"busNumber":864,"id":"","plateNumber":292241},
{"busNumber":863,"id":"","plateNumber":254270},
{"busNumber":862,"id":"","plateNumber":343779},
{"busNumber":861,"id":"","plateNumber":770175},
{"busNumber":860,"id":"","plateNumber":376308},
{"busNumber":859,"id":"","plateNumber":605102},
{"busNumber":858,"id":"","plateNumber":391429},
{"busNumber":857,"id":"","plateNumber":445408},
{"busNumber":856,"id":"","plateNumber":511946},
{"busNumber":855,"id":"","plateNumber":581583},
{"busNumber":854,"id":"","plateNumber":635806},
{"busNumber":853,"id":"","plateNumber":965611},
{"busNumber":852,"id":"","plateNumber":360936},
{"busNumber":851,"id":"","plateNumber":465311},
{"busNumber":850,"id":"","plateNumber":549395},
{"busNumber":849,"id":"","plateNumber":857493},
{"busNumber":848,"id":"","plateNumber":748892},
{"busNumber":847,"id":"","plateNumber":742493},
{"busNumber":846,"id":"","plateNumber":46315},
{"busNumber":845,"id":"","plateNumber":541757},
{"busNumber":844,"id":"","plateNumber":601173},
{"busNumber":843,"id":"","plateNumber":738964},
{"busNumber":842,"id":"","plateNumber":610676},
{"busNumber":841,"id":"","plateNumber":111554},
{"busNumber":840,"id":"","plateNumber":187154},
{"busNumber":839,"id":"","plateNumber":605576},
{"busNumber":838,"id":"","plateNumber":770805},
{"busNumber":837,"id":"","plateNumber":126192},
{"busNumber":836,"id":"","plateNumber":388883},
{"busNumber":835,"id":"","plateNumber":195182},
{"busNumber":834,"id":"","plateNumber":289446},
{"busNumber":833,"id":"","plateNumber":777194},
{"busNumber":832,"id":"","plateNumber":303087},
{"busNumber":831,"id":"","plateNumber":817343},
{"busNumber":830,"id":"","plateNumber":61107},
{"busNumber":829,"id":"","plateNumber":334987},
{"busNumber":828,"id":"","plateNumber":806579},
{"busNumber":827,"id":"","plateNumber":234995},
{"busNumber":826,"id":"","plateNumber":679033},
{"busNumber":825,"id":"","plateNumber":139135},
{"busNumber":824,"id":"","plateNumber":393490},
{"busNumber":823,"id":"","plateNumber":774254},
{"busNumber":822,"id":"","plateNumber":478947},
{"busNumber":821,"id":"","plateNumber":498403},
{"busNumber":820,"id":"","plateNumber":349107},
{"busNumber":819,"id":"","plateNumber":687052},
{"busNumber":818,"id":"","plateNumber":519681},
{"busNumber":817,"id":"","plateNumber":383075},
{"busNumber":816,"id":"","plateNumber":106020},
{"busNumber":815,"id":"","plateNumber":912705},
{"busNumber":814,"id":"","plateNumber":111820},
{"busNumber":813,"id":"","plateNumber":304238},
{"busNumber":812,"id":"","plateNumber":237371},
{"busNumber":811,"id":"","plateNumber":693843},
{"busNumber":810,"id":"","plateNumber":813539},
{"busNumber":809,"id":"","plateNumber":960309},
{"busNumber":808,"id":"","plateNumber":285716},
{"busNumber":807,"id":"","plateNumber":906600},
{"busNumber":806,"id":"","plateNumber":38186},
{"busNumber":805,"id":"","plateNumber":322708},
{"busNumber":804,"id":"","plateNumber":734938},
{"busNumber":803,"id":"","plateNumber":160265},
{"busNumber":802,"id":"","plateNumber":69310},
{"busNumber":801,"id":"","plateNumber":426461},
{"busNumber":800,"id":"","plateNumber":3868},
{"busNumber":799,"id":"","plateNumber":124963},
{"busNumber":798,"id":"","plateNumber":740127},
{"busNumber":797,"id":"","plateNumber":179080},
{"busNumber":796,"id":"","plateNumber":668694},
{"busNumber":795,"id":"","plateNumber":100259},
{"busNumber":794,"id":"","plateNumber":241791},
{"busNumber":793,"id":"","plateNumber":302895},
{"busNumber":792,"id":"","plateNumber":327164},
{"busNumber":791,"id":"","plateNumber":507952},
{"busNumber":790,"id":"","plateNumber":445931},
{"busNumber":789,"id":"","plateNumber":404904},
{"busNumber":788,"id":"","plateNumber":338240},
{"busNumber":787,"id":"","plateNumber":788816},
{"busNumber":786,"id":"","plateNumber":516055},
{"busNumber":785,"id":"","plateNumber":125267},
{"busNumber":784,"id":"","plateNumber":408687},
{"busNumber":783,"id":"","plateNumber":216920},
{"busNumber":782,"id":"","plateNumber":6880},
{"busNumber":781,"id":"","plateNumber":353029},
{"busNumber":780,"id":"","plateNumber":950464},
{"busNumber":779,"id":"","plateNumber":628637},
{"busNumber":778,"id":"","plateNumber":737391},
{"busNumber":777,"id":"","plateNumber":306869},
{"busNumber":776,"id":"","plateNumber":141115},
{"busNumber":775,"id":"","plateNumber":90464},
{"busNumber":774,"id":"","plateNumber":673204},
{"busNumber":773,"id":"","plateNumber":266257},
{"busNumber":772,"id":"","plateNumber":508364},
{"busNumber":771,"id":"","plateNumber":496348},
{"busNumber":770,"id":"","plateNumber":100444},
{"busNumber":769,"id":"","plateNumber":436476},
{"busNumber":768,"id":"","plateNumber":772373},
{"busNumber":767,"id":"","plateNumber":639796},
{"busNumber":766,"id":"","plateNumber":825197},
{"busNumber":765,"id":"","plateNumber":988443},
{"busNumber":764,"id":"","plateNumber":60761},
{"busNumber":763,"id":"","plateNumber":75919},
{"busNumber":762,"id":"","plateNumber":462851},
{"busNumber":761,"id":"","plateNumber":508156},
{"busNumber":760,"id":"","plateNumber":506968},
{"busNumber":759,"id":"","plateNumber":988791},
{"busNumber":758,"id":"","plateNumber":952759},
{"busNumber":757,"id":"","plateNumber":871503},
{"busNumber":756,"id":"","plateNumber":252085},
{"busNumber":755,"id":"","plateNumber":314955},
{"busNumber":754,"id":"","plateNumber":692690},
{"busNumber":753,"id":"","plateNumber":188360},
{"busNumber":752,"id":"","plateNumber":746200},
{"busNumber":751,"id":"","plateNumber":712242},
{"busNumber":750,"id":"","plateNumber":707786},
{"busNumber":749,"id":"","plateNumber":489206},
{"busNumber":748,"id":"","plateNumber":410968},
{"busNumber":747,"id":"","plateNumber":949112},
{"busNumber":746,"id":"","plateNumber":719562},
{"busNumber":745,"id":"","plateNumber":780418},
{"busNumber":744,"id":"","plateNumber":161825},
{"busNumber":743,"id":"","plateNumber":904258},
{"busNumber":742,"id":"","plateNumber":14816},
{"busNumber":741,"id":"","plateNumber":690272},
{"busNumber":740,"id":"","plateNumber":824320},
{"busNumber":739,"id":"","plateNumber":697837},
{"busNumber":738,"id":"","plateNumber":602259},
{"busNumber":737,"id":"","plateNumber":98966},
{"busNumber":736,"id":"","plateNumber":552090},
{"busNumber":735,"id":"","plateNumber":914889},
{"busNumber":734,"id":"","plateNumber":66036},
{"busNumber":733,"id":"","plateNumber":363776},
{"busNumber":732,"id":"","plateNumber":572512},
{"busNumber":731,"id":"","plateNumber":690690},
{"busNumber":730,"id":"","plateNumber":36050},
{"busNumber":729,"id":"","plateNumber":991308},
{"busNumber":728,"id":"","plateNumber":215589},
{"busNumber":727,"id":"","plateNumber":893371},
{"busNumber":726,"id":"","plateNumber":851697},
{"busNumber":725,"id":"","plateNumber":965360},
{"busNumber":724,"id":"","plateNumber":197604},
{"busNumber":723,"id":"","plateNumber":862739},
{"busNumber":722,"id":"","plateNumber":477668},
{"busNumber":721,"id":"","plateNumber":833625},
{"busNumber":720,"id":"","plateNumber":809813},
{"busNumber":719,"id":"","plateNumber":92511},
{"busNumber":718,"id":"","plateNumber":931912},
{"busNumber":717,"id":"","plateNumber":285919},
{"busNumber":716,"id":"","plateNumber":439314},
{"busNumber":715,"id":"","plateNumber":324411},
{"busNumber":714,"id":"","plateNumber":96608},
{"busNumber":713,"id":"","plateNumber":501004},
{"busNumber":712,"id":"","plateNumber":682072},
{"busNumber":711,"id":"","plateNumber":152973},
{"busNumber":710,"id":"","plateNumber":649567},
{"busNumber":709,"id":"","plateNumber":493514},
{"busNumber":708,"id":"","plateNumber":197214},
{"busNumber":707,"id":"","plateNumber":297351},
{"busNumber":706,"id":"","plateNumber":2910},
{"busNumber":705,"id":"","plateNumber":919356},
{"busNumber":704,"id":"","plateNumber":723606},
{"busNumber":703,"id":"","plateNumber":188016},
{"busNumber":702,"id":"","plateNumber":383954},
{"busNumber":701,"id":"","plateNumber":676813},
{"busNumber":700,"id":"","plateNumber":275730},
{"busNumber":699,"id":"","plateNumber":386820},
{"busNumber":698,"id":"","plateNumber":937644},
{"busNumber":697,"id":"","plateNumber":96987},
{"busNumber":696,"id":"","plateNumber":944133},
{"busNumber":695,"id":"","plateNumber":714565},
{"busNumber":694,"id":"","plateNumber":757599},
{"busNumber":693,"id":"","plateNumber":994499},
{"busNumber":692,"id":"","plateNumber":646619},
{"busNumber":691,"id":"","plateNumber":528860},
{"busNumber":690,"id":"","plateNumber":460897},
{"busNumber":689,"id":"","plateNumber":266748},
{"busNumber":688,"id":"","plateNumber":454654},
{"busNumber":687,"id":"","plateNumber":635541},
{"busNumber":686,"id":"","plateNumber":435275},
{"busNumber":685,"id":"","plateNumber":632638},
{"busNumber":684,"id":"","plateNumber":475703},
{"busNumber":683,"id":"","plateNumber":539900},
{"busNumber":682,"id":"","plateNumber":964515},
{"busNumber":681,"id":"","plateNumber":839403},
{"busNumber":680,"id":"","plateNumber":989854},
{"busNumber":679,"id":"","plateNumber":455651},
{"busNumber":678,"id":"","plateNumber":222951},
{"busNumber":677,"id":"","plateNumber":350310},
{"busNumber":676,"id":"","plateNumber":236899},
{"busNumber":675,"id":"","plateNumber":969964},
{"busNumber":674,"id":"","plateNumber":569730},
{"busNumber":673,"id":"","plateNumber":520790},
{"busNumber":672,"id":"","plateNumber":327890},
{"busNumber":671,"id":"","plateNumber":946028},
{"busNumber":670,"id":"","plateNumber":87946},
{"busNumber":669,"id":"","plateNumber":45525},
{"busNumber":668,"id":"","plateNumber":30965},
{"busNumber":667,"id":"","plateNumber":886388},
{"busNumber":666,"id":"","plateNumber":560495},
{"busNumber":665,"id":"","plateNumber":813574},
{"busNumber":664,"id":"","plateNumber":163387},
{"busNumber":663,"id":"","plateNumber":251},
{"busNumber":662,"id":"","plateNumber":594214},
{"busNumber":661,"id":"","plateNumber":302196},
{"busNumber":660,"id":"","plateNumber":966125},
{"busNumber":659,"id":"","plateNumber":716580},
{"busNumber":658,"id":"","plateNumber":224196},
{"busNumber":657,"id":"","plateNumber":799455},
{"busNumber":656,"id":"","plateNumber":906416},
{"busNumber":655,"id":"","plateNumber":624485},
{"busNumber":654,"id":"","plateNumber":243813},
{"busNumber":653,"id":"","plateNumber":643382},
{"busNumber":652,"id":"","plateNumber":464349},
{"busNumber":651,"id":"","plateNumber":779986},
{"busNumber":650,"id":"","plateNumber":93555},
{"busNumber":649,"id":"","plateNumber":370242},
{"busNumber":648,"id":"","plateNumber":956523},
{"busNumber":647,"id":"","plateNumber":894332},
{"busNumber":646,"id":"","plateNumber":676895},
{"busNumber":645,"id":"","plateNumber":566314},
{"busNumber":644,"id":"","plateNumber":75506},
{"busNumber":643,"id":"","plateNumber":663029},
{"busNumber":642,"id":"","plateNumber":629983},
{"busNumber":641,"id":"","plateNumber":670459},
{"busNumber":640,"id":"","plateNumber":155411},
{"busNumber":639,"id":"","plateNumber":159425},
{"busNumber":638,"id":"","plateNumber":518419},
{"busNumber":637,"id":"","plateNumber":621178},
{"busNumber":636,"id":"","plateNumber":842884},
{"busNumber":635,"id":"","plateNumber":912758},
{"busNumber":634,"id":"","plateNumber":52237},
{"busNumber":633,"id":"","plateNumber":594037},
{"busNumber":632,"id":"","plateNumber":167170},
{"busNumber":631,"id":"","plateNumber":476516},
{"busNumber":630,"id":"","plateNumber":846576},
{"busNumber":629,"id":"","plateNumber":276231},
{"busNumber":628,"id":"","plateNumber":812634},
{"busNumber":627,"id":"","plateNumber":844650},
{"busNumber":626,"id":"","plateNumber":782430},
{"busNumber":625,"id":"","plateNumber":357065},
{"busNumber":624,"id":"","plateNumber":267109},
{"busNumber":623,"id":"","plateNumber":442598},
{"busNumber":622,"id":"","plateNumber":939087},
{"busNumber":621,"id":"","plateNumber":128948},
{"busNumber":620,"id":"","plateNumber":360530},
{"busNumber":619,"id":"","plateNumber":911507},
{"busNumber":618,"id":"","plateNumber":352912},
{"busNumber":617,"id":"","plateNumber":415753},
{"busNumber":616,"id":"","plateNumber":863274},
{"busNumber":615,"id":"","plateNumber":609361},
{"busNumber":614,"id":"","plateNumber":761023},
{"busNumber":613,"id":"","plateNumber":20710},
{"busNumber":612,"id":"","plateNumber":533976},
{"busNumber":611,"id":"","plateNumber":364121},
{"busNumber":610,"id":"","plateNumber":529142},
{"busNumber":609,"id":"","plateNumber":8505},
{"busNumber":608,"id":"","plateNumber":416962},
{"busNumber":607,"id":"","plateNumber":165227},
{"busNumber":606,"id":"","plateNumber":770951},
{"busNumber":605,"id":"","plateNumber":874163},
{"busNumber":604,"id":"","plateNumber":412731},
{"busNumber":603,"id":"","plateNumber":624290},
{"busNumber":602,"id":"","plateNumber":142206},
{"busNumber":601,"id":"","plateNumber":847249},
{"busNumber":600,"id":"","plateNumber":631715},
{"busNumber":599,"id":"","plateNumber":83217},
{"busNumber":598,"id":"","plateNumber":673568},
{"busNumber":597,"id":"","plateNumber":193160},
{"busNumber":596,"id":"","plateNumber":892137},
{"busNumber":595,"id":"","plateNumber":592876},
{"busNumber":594,"id":"","plateNumber":296644},
{"busNumber":593,"id":"","plateNumber":152810},
{"busNumber":592,"id":"","plateNumber":90395},
{"busNumber":591,"id":"","plateNumber":653696},
{"busNumber":590,"id":"","plateNumber":740502},
{"busNumber":589,"id":"","plateNumber":949059},
{"busNumber":588,"id":"","plateNumber":593346},
{"busNumber":587,"id":"","plateNumber":13378},
{"busNumber":586,"id":"","plateNumber":893034},
{"busNumber":585,"id":"","plateNumber":869118},
{"busNumber":584,"id":"","plateNumber":196729},
{"busNumber":583,"id":"","plateNumber":660761},
{"busNumber":582,"id":"","plateNumber":764442},
{"busNumber":581,"id":"","plateNumber":398772},
{"busNumber":580,"id":"","plateNumber":204883},
{"busNumber":579,"id":"","plateNumber":896785},
{"busNumber":578,"id":"","plateNumber":433839},
{"busNumber":577,"id":"","plateNumber":9444},
{"busNumber":576,"id":"","plateNumber":772007},
{"busNumber":575,"id":"","plateNumber":691905},
{"busNumber":574,"id":"","plateNumber":834815},
{"busNumber":573,"id":"","plateNumber":825035},
{"busNumber":572,"id":"","plateNumber":745615},
{"busNumber":571,"id":"","plateNumber":861661},
{"busNumber":570,"id":"","plateNumber":74352},
{"busNumber":569,"id":"","plateNumber":30617},
{"busNumber":568,"id":"","plateNumber":141731},
{"busNumber":567,"id":"","plateNumber":368401},
{"busNumber":566,"id":"","plateNumber":281325},
{"busNumber":565,"id":"","plateNumber":2499},
{"busNumber":564,"id":"","plateNumber":856653},
{"busNumber":563,"id":"","plateNumber":730153},
{"busNumber":562,"id":"","plateNumber":848650},
{"busNumber":561,"id":"","plateNumber":336174},
{"busNumber":560,"id":"","plateNumber":75984},
{"busNumber":559,"id":"","plateNumber":224605},
{"busNumber":558,"id":"","plateNumber":920759},
{"busNumber":557,"id":"","plateNumber":57065},
{"busNumber":556,"id":"","plateNumber":351418},
{"busNumber":555,"id":"","plateNumber":843199},
{"busNumber":554,"id":"","plateNumber":246950},
{"busNumber":553,"id":"","plateNumber":842171},
{"busNumber":552,"id":"","plateNumber":343502},
{"busNumber":551,"id":"","plateNumber":707241},
{"busNumber":550,"id":"","plateNumber":115639},
{"busNumber":549,"id":"","plateNumber":818354},
{"busNumber":548,"id":"","plateNumber":774629},
{"busNumber":547,"id":"","plateNumber":852693},
{"busNumber":546,"id":"","plateNumber":337861},
{"busNumber":545,"id":"","plateNumber":576565},
{"busNumber":544,"id":"","plateNumber":937992},
{"busNumber":543,"id":"","plateNumber":321150},
{"busNumber":542,"id":"","plateNumber":255856},
{"busNumber":541,"id":"","plateNumber":313520},
{"busNumber":540,"id":"","plateNumber":41484},
{"busNumber":539,"id":"","plateNumber":905219},
{"busNumber":538,"id":"","plateNumber":65762},
{"busNumber":537,"id":"","plateNumber":800478},
{"busNumber":536,"id":"","plateNumber":156389},
{"busNumber":535,"id":"","plateNumber":162279},
{"busNumber":534,"id":"","plateNumber":541157},
{"busNumber":533,"id":"","plateNumber":222693},
{"busNumber":532,"id":"","plateNumber":239712},
{"busNumber":531,"id":"","plateNumber":817078},
{"busNumber":530,"id":"","plateNumber":524493},
{"busNumber":529,"id":"","plateNumber":430260},
{"busNumber":528,"id":"","plateNumber":522579},
{"busNumber":527,"id":"","plateNumber":471809},
{"busNumber":526,"id":"","plateNumber":71895},
{"busNumber":525,"id":"","plateNumber":650753},
{"busNumber":524,"id":"","plateNumber":297537},
{"busNumber":523,"id":"","plateNumber":184668},
{"busNumber":522,"id":"","plateNumber":813952},
{"busNumber":521,"id":"","plateNumber":794951},
{"busNumber":520,"id":"","plateNumber":805765},
{"busNumber":519,"id":"","plateNumber":33596},
{"busNumber":518,"id":"","plateNumber":25471},
{"busNumber":517,"id":"","plateNumber":444613},
{"busNumber":516,"id":"","plateNumber":154506},
{"busNumber":515,"id":"","plateNumber":870976},
{"busNumber":514,"id":"","plateNumber":930451},
{"busNumber":513,"id":"","plateNumber":166526},
{"busNumber":512,"id":"","plateNumber":749858},
{"busNumber":511,"id":"","plateNumber":71550},
{"busNumber":510,"id":"","plateNumber":611891},
{"busNumber":509,"id":"","plateNumber":696449},
{"busNumber":508,"id":"","plateNumber":226428},
{"busNumber":507,"id":"","plateNumber":580794},
{"busNumber":506,"id":"","plateNumber":576209},
{"busNumber":505,"id":"","plateNumber":96676},
{"busNumber":504,"id":"","plateNumber":933348},
{"busNumber":503,"id":"","plateNumber":822272},
{"busNumber":502,"id":"","plateNumber":669827},
{"busNumber":501,"id":"","plateNumber":384462},
{"busNumber":500,"id":"","plateNumber":223619},
{"busNumber":499,"id":"","plateNumber":186721},
{"busNumber":498,"id":"","plateNumber":53532},
{"busNumber":497,"id":"","plateNumber":411669},
{"busNumber":496,"id":"","plateNumber":603947},
{"busNumber":495,"id":"","plateNumber":376636},
{"busNumber":494,"id":"","plateNumber":555529},
{"busNumber":493,"id":"","plateNumber":629117},
{"busNumber":492,"id":"","plateNumber":785916},
{"busNumber":491,"id":"","plateNumber":441154},
{"busNumber":490,"id":"","plateNumber":523640},
{"busNumber":489,"id":"","plateNumber":317350},
{"busNumber":488,"id":"","plateNumber":602209},
{"busNumber":487,"id":"","plateNumber":742635},
{"busNumber":486,"id":"","plateNumber":348545},
{"busNumber":485,"id":"","plateNumber":446327},
{"busNumber":484,"id":"","plateNumber":56832},
{"busNumber":483,"id":"","plateNumber":180087},
{"busNumber":482,"id":"","plateNumber":551950},
{"busNumber":481,"id":"","plateNumber":287661},
{"busNumber":480,"id":"","plateNumber":568368},
{"busNumber":479,"id":"","plateNumber":118301},
{"busNumber":478,"id":"","plateNumber":202067},
{"busNumber":477,"id":"","plateNumber":535515},
{"busNumber":476,"id":"","plateNumber":190326},
{"busNumber":475,"id":"","plateNumber":827935},
{"busNumber":474,"id":"","plateNumber":816812},
{"busNumber":473,"id":"","plateNumber":147212},
{"busNumber":472,"id":"","plateNumber":687400},
{"busNumber":471,"id":"","plateNumber":800221},
{"busNumber":470,"id":"","plateNumber":361266},
{"busNumber":469,"id":"","plateNumber":966261},
{"busNumber":468,"id":"","plateNumber":246893},
{"busNumber":467,"id":"","plateNumber":602202},
{"busNumber":466,"id":"","plateNumber":782824},
{"busNumber":465,"id":"","plateNumber":885571},
{"busNumber":464,"id":"","plateNumber":763697},
{"busNumber":463,"id":"","plateNumber":447027},
{"busNumber":462,"id":"","plateNumber":631026},
{"busNumber":461,"id":"","plateNumber":951534},
{"busNumber":460,"id":"","plateNumber":714659},
{"busNumber":459,"id":"","plateNumber":61973},
{"busNumber":458,"id":"","plateNumber":921404},
{"busNumber":457,"id":"","plateNumber":522535},
{"busNumber":456,"id":"","plateNumber":894031},
{"busNumber":455,"id":"","plateNumber":946902},
{"busNumber":454,"id":"","plateNumber":106105},
{"busNumber":453,"id":"","plateNumber":422738},
{"busNumber":452,"id":"","plateNumber":731749},
{"busNumber":451,"id":"","plateNumber":19774},
{"busNumber":450,"id":"","plateNumber":379285},
{"busNumber":449,"id":"","plateNumber":695365},
{"busNumber":448,"id":"","plateNumber":934726},
{"busNumber":447,"id":"","plateNumber":546221},
{"busNumber":446,"id":"","plateNumber":884786},
{"busNumber":445,"id":"","plateNumber":371361},
{"busNumber":444,"id":"","plateNumber":422871},
{"busNumber":443,"id":"","plateNumber":407102},
{"busNumber":442,"id":"","plateNumber":82561},
{"busNumber":441,"id":"","plateNumber":696715},
{"busNumber":440,"id":"","plateNumber":671563},
{"busNumber":439,"id":"","plateNumber":370034},
{"busNumber":438,"id":"","plateNumber":999280},
{"busNumber":437,"id":"","plateNumber":442640},
{"busNumber":436,"id":"","plateNumber":811570},
{"busNumber":435,"id":"","plateNumber":692701},
{"busNumber":434,"id":"","plateNumber":892493},
{"busNumber":433,"id":"","plateNumber":828661},
{"busNumber":432,"id":"","plateNumber":757222},
{"busNumber":431,"id":"","plateNumber":437620},
{"busNumber":430,"id":"","plateNumber":916919},
{"busNumber":429,"id":"","plateNumber":926852},
{"busNumber":428,"id":"","plateNumber":887768},
{"busNumber":427,"id":"","plateNumber":316738},
{"busNumber":426,"id":"","plateNumber":524709},
{"busNumber":425,"id":"","plateNumber":369345},
{"busNumber":424,"id":"","plateNumber":20197},
{"busNumber":423,"id":"","plateNumber":398555},
{"busNumber":422,"id":"","plateNumber":177290},
{"busNumber":421,"id":"","plateNumber":234922},
{"busNumber":420,"id":"","plateNumber":855279},
{"busNumber":419,"id":"","plateNumber":106804},
{"busNumber":418,"id":"","plateNumber":412909},
{"busNumber":417,"id":"","plateNumber":994314},
{"busNumber":416,"id":"","plateNumber":868188},
{"busNumber":415,"id":"","plateNumber":591945},
{"busNumber":414,"id":"","plateNumber":195291},
{"busNumber":413,"id":"","plateNumber":461837},
{"busNumber":412,"id":"","plateNumber":183283},
{"busNumber":411,"id":"","plateNumber":8288},
{"busNumber":410,"id":"","plateNumber":770892},
{"busNumber":409,"id":"","plateNumber":590685},
{"busNumber":408,"id":"","plateNumber":341905},
{"busNumber":407,"id":"","plateNumber":924639},
{"busNumber":406,"id":"","plateNumber":27686},
{"busNumber":405,"id":"","plateNumber":719063},
{"busNumber":404,"id":"","plateNumber":304816},
{"busNumber":403,"id":"","plateNumber":327380},
{"busNumber":402,"id":"","plateNumber":57653},
{"busNumber":401,"id":"","plateNumber":187803},
{"busNumber":400,"id":"","plateNumber":443584},
{"busNumber":399,"id":"","plateNumber":724840},
{"busNumber":398,"id":"","plateNumber":349298},
{"busNumber":397,"id":"","plateNumber":124216},
{"busNumber":396,"id":"","plateNumber":847644},
{"busNumber":395,"id":"","plateNumber":249762},
{"busNumber":394,"id":"","plateNumber":31424},
{"busNumber":393,"id":"","plateNumber":356441},
{"busNumber":392,"id":"","plateNumber":314971},
{"busNumber":391,"id":"","plateNumber":334530},
{"busNumber":390,"id":"","plateNumber":598937},
{"busNumber":389,"id":"","plateNumber":168844},
{"busNumber":388,"id":"","plateNumber":896481},
{"busNumber":387,"id":"","plateNumber":996473},
{"busNumber":386,"id":"","plateNumber":877270},
{"busNumber":385,"id":"","plateNumber":309644},
{"busNumber":384,"id":"","plateNumber":600468},
{"busNumber":383,"id":"","plateNumber":221676},
{"busNumber":382,"id":"","plateNumber":373292},
{"busNumber":381,"id":"","plateNumber":326715},
{"busNumber":380,"id":"","plateNumber":432784},
{"busNumber":379,"id":"","plateNumber":589237},
{"busNumber":378,"id":"","plateNumber":912228},
{"busNumber":377,"id":"","plateNumber":739582},
{"busNumber":376,"id":"","plateNumber":845004},
{"busNumber":375,"id":"","plateNumber":405927},
{"busNumber":374,"id":"","plateNumber":204252},
{"busNumber":373,"id":"","plateNumber":937956},
{"busNumber":372,"id":"","plateNumber":674410},
{"busNumber":371,"id":"","plateNumber":780785},
{"busNumber":370,"id":"","plateNumber":746599},
{"busNumber":369,"id":"","plateNumber":873774},
{"busNumber":368,"id":"","plateNumber":567801},
{"busNumber":367,"id":"","plateNumber":376137},
{"busNumber":366,"id":"","plateNumber":306097},
{"busNumber":365,"id":"","plateNumber":762574},
{"busNumber":364,"id":"","plateNumber":527677},
{"busNumber":363,"id":"","plateNumber":356419},
{"busNumber":362,"id":"","plateNumber":618345},
{"busNumber":361,"id":"","plateNumber":942554},
{"busNumber":360,"id":"","plateNumber":698055},
{"busNumber":359,"id":"","plateNumber":729949},
{"busNumber":358,"id":"","plateNumber":922801},
{"busNumber":357,"id":"","plateNumber":129616},
{"busNumber":356,"id":"","plateNumber":184453},
{"busNumber":355,"id":"","plateNumber":833648},
{"busNumber":354,"id":"","plateNumber":446922},
{"busNumber":353,"id":"","plateNumber":406813},
{"busNumber":352,"id":"","plateNumber":348620},
{"busNumber":351,"id":"","plateNumber":559888},
{"busNumber":350,"id":"","plateNumber":82217},
{"busNumber":349,"id":"","plateNumber":479103},
{"busNumber":348,"id":"","plateNumber":621217},
{"busNumber":347,"id":"","plateNumber":80603},
{"busNumber":346,"id":"","plateNumber":603555},
{"busNumber":345,"id":"","plateNumber":960599},
{"busNumber":344,"id":"","plateNumber":548308},
{"busNumber":343,"id":"","plateNumber":428329},
{"busNumber":342,"id":"","plateNumber":165686},
{"busNumber":341,"id":"","plateNumber":553337},
{"busNumber":340,"id":"","plateNumber":256907},
{"busNumber":339,"id":"","plateNumber":703618},
{"busNumber":338,"id":"","plateNumber":891665},
{"busNumber":337,"id":"","plateNumber":209544},
{"busNumber":336,"id":"","plateNumber":95876},
{"busNumber":335,"id":"","plateNumber":949073},
{"busNumber":334,"id":"","plateNumber":116674},
{"busNumber":333,"id":"","plateNumber":213263},
{"busNumber":332,"id":"","plateNumber":253424},
{"busNumber":331,"id":"","plateNumber":284345},
{"busNumber":330,"id":"","plateNumber":320465},
{"busNumber":329,"id":"","plateNumber":497778},
{"busNumber":328,"id":"","plateNumber":171363},
{"busNumber":327,"id":"","plateNumber":978395},
{"busNumber":326,"id":"","plateNumber":40591},
{"busNumber":325,"id":"","plateNumber":221035},
{"busNumber":324,"id":"","plateNumber":461505},
{"busNumber":323,"id":"","plateNumber":438966},
{"busNumber":322,"id":"","plateNumber":124931},
{"busNumber":321,"id":"","plateNumber":140753},
{"busNumber":320,"id":"","plateNumber":249136},
{"busNumber":319,"id":"","plateNumber":245606},
{"busNumber":318,"id":"","plateNumber":16265},
{"busNumber":317,"id":"","plateNumber":719775},
{"busNumber":316,"id":"","plateNumber":245457},
{"busNumber":315,"id":"","plateNumber":259150},
{"busNumber":314,"id":"","plateNumber":571246},
{"busNumber":313,"id":"","plateNumber":493346},
{"busNumber":312,"id":"","plateNumber":229650},
{"busNumber":311,"id":"","plateNumber":651586},
{"busNumber":310,"id":"","plateNumber":896443},
{"busNumber":309,"id":"","plateNumber":110515},
{"busNumber":308,"id":"","plateNumber":875763},
{"busNumber":307,"id":"","plateNumber":169533},
{"busNumber":306,"id":"","plateNumber":59216},
{"busNumber":305,"id":"","plateNumber":639291},
{"busNumber":304,"id":"","plateNumber":61737},
{"busNumber":303,"id":"","plateNumber":920288},
{"busNumber":302,"id":"","plateNumber":433688},
{"busNumber":301,"id":"","plateNumber":73440},
{"busNumber":300,"id":"","plateNumber":211579},
{"busNumber":299,"id":"","plateNumber":997494},
{"busNumber":298,"id":"","plateNumber":331395},
{"busNumber":297,"id":"","plateNumber":654679},
{"busNumber":296,"id":"","plateNumber":469207},
{"busNumber":295,"id":"","plateNumber":18390},
{"busNumber":294,"id":"","plateNumber":758330},
{"busNumber":293,"id":"","plateNumber":192677},
{"busNumber":292,"id":"","plateNumber":892990},
{"busNumber":291,"id":"","plateNumber":326599},
{"busNumber":290,"id":"","plateNumber":991418},
{"busNumber":289,"id":"","plateNumber":975553},
{"busNumber":288,"id":"","plateNumber":174413},
{"busNumber":287,"id":"","plateNumber":621691},
{"busNumber":286,"id":"","plateNumber":732154},
{"busNumber":285,"id":"","plateNumber":561577},
{"busNumber":284,"id":"","plateNumber":50},
{"busNumber":283,"id":"","plateNumber":933113},
{"busNumber":282,"id":"","plateNumber":814012},
{"busNumber":281,"id":"","plateNumber":985514},
{"busNumber":280,"id":"","plateNumber":865426},
{"busNumber":279,"id":"","plateNumber":743613},
{"busNumber":278,"id":"","plateNumber":346900},
{"busNumber":277,"id":"","plateNumber":502219},
{"busNumber":276,"id":"","plateNumber":522075},
{"busNumber":275,"id":"","plateNumber":165540},
{"busNumber":274,"id":"","plateNumber":502530},
{"busNumber":273,"id":"","plateNumber":858609},
{"busNumber":272,"id":"","plateNumber":758848},
{"busNumber":271,"id":"","plateNumber":741355},
{"busNumber":270,"id":"","plateNumber":649353},
{"busNumber":269,"id":"","plateNumber":147103},
{"busNumber":268,"id":"","plateNumber":54476},
{"busNumber":267,"id":"","plateNumber":990589},
{"busNumber":266,"id":"","plateNumber":459670},
{"busNumber":265,"id":"","plateNumber":901595},
{"busNumber":264,"id":"","plateNumber":93016},
{"busNumber":263,"id":"","plateNumber":233887},
{"busNumber":262,"id":"","plateNumber":587237},
{"busNumber":261,"id":"","plateNumber":440701},
{"busNumber":260,"id":"","plateNumber":523572},
{"busNumber":259,"id":"","plateNumber":544783},
{"busNumber":258,"id":"","plateNumber":918609},
{"busNumber":257,"id":"","plateNumber":539870},
{"busNumber":256,"id":"","plateNumber":373450},
{"busNumber":255,"id":"","plateNumber":480992},
{"busNumber":254,"id":"","plateNumber":618368},
{"busNumber":253,"id":"","plateNumber":357178},
{"busNumber":252,"id":"","plateNumber":386023},
{"busNumber":251,"id":"","plateNumber":761194},
{"busNumber":250,"id":"","plateNumber":928752},
{"busNumber":249,"id":"","plateNumber":598954},
{"busNumber":248,"id":"","plateNumber":113619},
{"busNumber":247,"id":"","plateNumber":307820},
{"busNumber":246,"id":"","plateNumber":756778},
{"busNumber":245,"id":"","plateNumber":376152},
{"busNumber":244,"id":"","plateNumber":168706},
{"busNumber":243,"id":"","plateNumber":185694},
{"busNumber":242,"id":"","plateNumber":661073},
{"busNumber":241,"id":"","plateNumber":810992},
{"busNumber":240,"id":"","plateNumber":897353},
{"busNumber":239,"id":"","plateNumber":167612},
{"busNumber":238,"id":"","plateNumber":501763},
{"busNumber":237,"id":"","plateNumber":46034},
{"busNumber":236,"id":"","plateNumber":481214},
{"busNumber":235,"id":"","plateNumber":57206},
{"busNumber":234,"id":"","plateNumber":184691},
{"busNumber":233,"id":"","plateNumber":787679},
{"busNumber":232,"id":"","plateNumber":330277},
{"busNumber":231,"id":"","plateNumber":504166},
{"busNumber":230,"id":"","plateNumber":540992},
{"busNumber":229,"id":"","plateNumber":133008},
{"busNumber":228,"id":"","plateNumber":142956},
{"busNumber":227,"id":"","plateNumber":468117},
{"busNumber":226,"id":"","plateNumber":637277},
{"busNumber":225,"id":"","plateNumber":990240},
{"busNumber":224,"id":"","plateNumber":946330},
{"busNumber":223,"id":"","plateNumber":4589},
{"busNumber":222,"id":"","plateNumber":318348},
{"busNumber":221,"id":"","plateNumber":979537},
{"busNumber":220,"id":"","plateNumber":105330},
{"busNumber":219,"id":"","plateNumber":565110},
{"busNumber":218,"id":"","plateNumber":435879},
{"busNumber":217,"id":"","plateNumber":778086},
{"busNumber":216,"id":"","plateNumber":883258},
{"busNumber":215,"id":"","plateNumber":864397},
{"busNumber":214,"id":"","plateNumber":436044},
{"busNumber":213,"id":"","plateNumber":400237},
{"busNumber":212,"id":"","plateNumber":700290},
{"busNumber":211,"id":"","plateNumber":567477},
{"busNumber":210,"id":"","plateNumber":50853},
{"busNumber":209,"id":"","plateNumber":241778},
{"busNumber":208,"id":"","plateNumber":72958},
{"busNumber":207,"id":"","plateNumber":482805},
{"busNumber":206,"id":"","plateNumber":840299},
{"busNumber":205,"id":"","plateNumber":170243},
{"busNumber":204,"id":"","plateNumber":104244},
{"busNumber":203,"id":"","plateNumber":293702},
{"busNumber":202,"id":"","plateNumber":252591},
{"busNumber":201,"id":"","plateNumber":52542},
{"busNumber":200,"id":"","plateNumber":755039},
{"busNumber":199,"id":"","plateNumber":653264},
{"busNumber":198,"id":"","plateNumber":788726},
{"busNumber":197,"id":"","plateNumber":67738},
{"busNumber":196,"id":"","plateNumber":358588},
{"busNumber":195,"id":"","plateNumber":170282},
{"busNumber":194,"id":"","plateNumber":80819},
{"busNumber":193,"id":"","plateNumber":219950},
{"busNumber":192,"id":"","plateNumber":210211},
{"busNumber":191,"id":"","plateNumber":874408},
{"busNumber":190,"id":"","plateNumber":373102},
{"busNumber":189,"id":"","plateNumber":85986},
{"busNumber":188,"id":"","plateNumber":167152},
{"busNumber":187,"id":"","plateNumber":747725},
{"busNumber":186,"id":"","plateNumber":194858},
{"busNumber":185,"id":"","plateNumber":143877},
{"busNumber":184,"id":"","plateNumber":168072},
{"busNumber":183,"id":"","plateNumber":632530},
{"busNumber":182,"id":"","plateNumber":817654},
{"busNumber":181,"id":"","plateNumber":702236},
{"busNumber":180,"id":"","plateNumber":523395},
{"busNumber":179,"id":"","plateNumber":856565},
{"busNumber":178,"id":"","plateNumber":877818},
{"busNumber":177,"id":"","plateNumber":852977},
{"busNumber":176,"id":"","plateNumber":473159},
{"busNumber":175,"id":"","plateNumber":726309},
{"busNumber":174,"id":"","plateNumber":574584},
{"busNumber":173,"id":"","plateNumber":558216},
{"busNumber":172,"id":"","plateNumber":801334},
{"busNumber":171,"id":"","plateNumber":303744},
{"busNumber":170,"id":"","plateNumber":528180},
{"busNumber":169,"id":"","plateNumber":46356},
{"busNumber":168,"id":"","plateNumber":864090},
{"busNumber":167,"id":"","plateNumber":598136},
{"busNumber":166,"id":"","plateNumber":75301},
{"busNumber":165,"id":"","plateNumber":954514},
{"busNumber":164,"id":"","plateNumber":453519},
{"busNumber":163,"id":"","plateNumber":525990},
{"busNumber":162,"id":"","plateNumber":662042},
{"busNumber":161,"id":"","plateNumber":383677},
{"busNumber":160,"id":"","plateNumber":449272},
{"busNumber":159,"id":"","plateNumber":551084},
{"busNumber":158,"id":"","plateNumber":114245},
{"busNumber":157,"id":"","plateNumber":145021},
{"busNumber":156,"id":"","plateNumber":744083},
{"busNumber":155,"id":"","plateNumber":843122},
{"busNumber":154,"id":"","plateNumber":633273},
{"busNumber":153,"id":"","plateNumber":297513},
{"busNumber":152,"id":"","plateNumber":40733},
{"busNumber":151,"id":"","plateNumber":735656},
{"busNumber":150,"id":"","plateNumber":415596},
{"busNumber":149,"id":"","plateNumber":341093},
{"busNumber":148,"id":"","plateNumber":724738},
{"busNumber":147,"id":"","plateNumber":296658},
{"busNumber":146,"id":"","plateNumber":206989},
{"busNumber":145,"id":"","plateNumber":73121},
{"busNumber":144,"id":"","plateNumber":536406},
{"busNumber":143,"id":"","plateNumber":779160},
{"busNumber":142,"id":"","plateNumber":171845},
{"busNumber":141,"id":"","plateNumber":306114},
{"busNumber":140,"id":"","plateNumber":560843},
{"busNumber":139,"id":"","plateNumber":734293},
{"busNumber":138,"id":"","plateNumber":195911},
{"busNumber":137,"id":"","plateNumber":932219},
{"busNumber":136,"id":"","plateNumber":516174},
{"busNumber":135,"id":"","plateNumber":624072},
{"busNumber":134,"id":"","plateNumber":928636},
{"busNumber":133,"id":"","plateNumber":458825},
{"busNumber":132,"id":"","plateNumber":334318},
{"busNumber":131,"id":"","plateNumber":848281},
{"busNumber":130,"id":"","plateNumber":860457},
{"busNumber":129,"id":"","plateNumber":634251},
{"busNumber":128,"id":"","plateNumber":369524},
{"busNumber":127,"id":"","plateNumber":562754},
{"busNumber":126,"id":"","plateNumber":398277},
{"busNumber":125,"id":"","plateNumber":644766},
{"busNumber":124,"id":"","plateNumber":572503},
{"busNumber":123,"id":"","plateNumber":40029},
{"busNumber":122,"id":"","plateNumber":22161},
{"busNumber":121,"id":"","plateNumber":492080},
{"busNumber":120,"id":"","plateNumber":821671},
{"busNumber":119,"id":"","plateNumber":546525},
{"busNumber":118,"id":"","plateNumber":594056},
{"busNumber":117,"id":"","plateNumber":5907},
{"busNumber":116,"id":"","plateNumber":526794},
{"busNumber":115,"id":"","plateNumber":249944},
{"busNumber":114,"id":"","plateNumber":605519},
{"busNumber":113,"id":"","plateNumber":59272},
{"busNumber":112,"id":"","plateNumber":708807},
{"busNumber":111,"id":"","plateNumber":36044},
{"busNumber":110,"id":"","plateNumber":864640},
{"busNumber":109,"id":"","plateNumber":180287},
{"busNumber":108,"id":"","plateNumber":888549},
{"busNumber":107,"id":"","plateNumber":863196},
{"busNumber":106,"id":"","plateNumber":612826},
{"busNumber":105,"id":"","plateNumber":541047},
{"busNumber":104,"id":"","plateNumber":583645},
{"busNumber":103,"id":"","plateNumber":124242},
{"busNumber":102,"id":"","plateNumber":807461},
{"busNumber":101,"id":"","plateNumber":949032},
{"busNumber":100,"id":"","plateNumber":31905},
{"busNumber":99,"id":"","plateNumber":744963},
{"busNumber":98,"id":"","plateNumber":959161},
{"busNumber":97,"id":"","plateNumber":40388},
{"busNumber":96,"id":"","plateNumber":779092},
{"busNumber":95,"id":"","plateNumber":680609},
{"busNumber":94,"id":"","plateNumber":445099},
{"busNumber":93,"id":"","plateNumber":27692},
{"busNumber":92,"id":"","plateNumber":584135},
{"busNumber":91,"id":"","plateNumber":691905},
{"busNumber":90,"id":"","plateNumber":250705},
{"busNumber":89,"id":"","plateNumber":90357},
{"busNumber":88,"id":"","plateNumber":820118},
{"busNumber":87,"id":"","plateNumber":969998},
{"busNumber":86,"id":"","plateNumber":688535},
{"busNumber":85,"id":"","plateNumber":665956},
{"busNumber":84,"id":"","plateNumber":586665},
{"busNumber":83,"id":"","plateNumber":884569},
{"busNumber":82,"id":"","plateNumber":731381},
{"busNumber":81,"id":"","plateNumber":524387},
{"busNumber":80,"id":"","plateNumber":614965},
{"busNumber":79,"id":"","plateNumber":847072},
{"busNumber":78,"id":"","plateNumber":511331},
{"busNumber":77,"id":"","plateNumber":645331},
{"busNumber":76,"id":"","plateNumber":830010},
{"busNumber":75,"id":"","plateNumber":219472},
{"busNumber":74,"id":"","plateNumber":536538},
{"busNumber":73,"id":"","plateNumber":723473},
{"busNumber":72,"id":"","plateNumber":412885},
{"busNumber":71,"id":"","plateNumber":903912},
{"busNumber":70,"id":"","plateNumber":324201},
{"busNumber":69,"id":"","plateNumber":860644},
{"busNumber":68,"id":"","plateNumber":717895},
{"busNumber":67,"id":"","plateNumber":174246},
{"busNumber":66,"id":"","plateNumber":865349},
{"busNumber":65,"id":"","plateNumber":615036},
{"busNumber":64,"id":"","plateNumber":967060},
{"busNumber":63,"id":"","plateNumber":16560},
{"busNumber":62,"id":"","plateNumber":163765},
{"busNumber":61,"id":"","plateNumber":826165},
{"busNumber":60,"id":"","plateNumber":941519},
{"busNumber":59,"id":"","plateNumber":161804},
{"busNumber":58,"id":"","plateNumber":815942},
{"busNumber":57,"id":"","plateNumber":554247},
{"busNumber":56,"id":"","plateNumber":99621},
{"busNumber":55,"id":"","plateNumber":413165},
{"busNumber":54,"id":"","plateNumber":995065},
{"busNumber":53,"id":"","plateNumber":384381},
{"busNumber":52,"id":"","plateNumber":311325},
{"busNumber":51,"id":"","plateNumber":245458},
{"busNumber":50,"id":"","plateNumber":722569},
{"busNumber":49,"id":"","plateNumber":48191},
{"busNumber":48,"id":"","plateNumber":379600},
{"busNumber":47,"id":"","plateNumber":256996},
{"busNumber":46,"id":"","plateNumber":627626},
{"busNumber":45,"id":"","plateNumber":835901},
{"busNumber":44,"id":"","plateNumber":211962},
{"busNumber":43,"id":"","plateNumber":430429},
{"busNumber":42,"id":"","plateNumber":636019},
{"busNumber":41,"id":"","plateNumber":325983},
{"busNumber":40,"id":"","plateNumber":89775},
{"busNumber":39,"id":"","plateNumber":845601},
{"busNumber":38,"id":"","plateNumber":531920},
{"busNumber":37,"id":"","plateNumber":452558},
{"busNumber":36,"id":"","plateNumber":191624},
{"busNumber":35,"id":"","plateNumber":883961},
{"busNumber":34,"id":"","plateNumber":276676},
{"busNumber":33,"id":"","plateNumber":590898},
{"busNumber":32,"id":"","plateNumber":282089},
{"busNumber":31,"id":"","plateNumber":596298},
{"busNumber":30,"id":"","plateNumber":526764},
{"busNumber":29,"id":"","plateNumber":9048},
{"busNumber":28,"id":"","plateNumber":615213},
{"busNumber":27,"id":"","plateNumber":58487},
{"busNumber":26,"id":"","plateNumber":42757},
{"busNumber":25,"id":"","plateNumber":443736},
{"busNumber":24,"id":"","plateNumber":240634},
{"busNumber":23,"id":"","plateNumber":499583},
{"busNumber":22,"id":"","plateNumber":945365},
{"busNumber":21,"id":"","plateNumber":596567},
{"busNumber":20,"id":"","plateNumber":207384},
{"busNumber":19,"id":"","plateNumber":58840},
{"busNumber":18,"id":"","plateNumber":60028},
{"busNumber":17,"id":"","plateNumber":374420},
{"busNumber":16,"id":"","plateNumber":104610},
{"busNumber":15,"id":"","plateNumber":157631},
{"busNumber":14,"id":"","plateNumber":996916},
{"busNumber":13,"id":"","plateNumber":154549},
{"busNumber":12,"id":"","plateNumber":465873},
{"busNumber":11,"id":"","plateNumber":139458},
{"busNumber":10,"id":"","plateNumber":365442},
{"busNumber":9,"id":"","plateNumber":853249},
{"busNumber":8,"id":"","plateNumber":556569},
{"busNumber":7,"id":"","plateNumber":898537},
{"busNumber":6,"id":"","plateNumber":128454},
{"busNumber":5,"id":"","plateNumber":132606},
{"busNumber":4,"id":"","plateNumber":448408},
{"busNumber":3,"id":"","plateNumber":249993},
{"busNumber":2,"id":"","plateNumber":355948},
{"busNumber":1,"id":"","plateNumber":617283}
]