export * from './buy';
export * from './Main';
export * from './pay';
export * from './paypal1';
export * from './person';
export * from './sales-policies-check';
export * from './schedules1';
export * from './select-seats';
export * from './ticketPage';
